Repository ember-learn/guides-source, pull requests merged in 2018-12, with the labels that each got.

#291 Adds Handlebars explainer paragraph
  guides/v2.10.0/tutorial/simple-component.md
Labels: needs a reviewer

#288 Models: reformulate the JSON/API content
  guides/v3.5.0/models/index.md
Labels: needs contributor response

#247 Update link to 'a word on promises'
  guides/v3.5.0/glossary/web-development.md
Labels: needs contributor response

#313 Update js-primer.md
  guides/v3.5.0/getting-started/js-primer.md
  guides/v3.6.0/getting-started/js-primer.md
Labels: Needs to be added to the release

#318 Update embedding-applications.md
  guides/v3.5.0/configuring-ember/embedding-applications.md
Labels: Needs to be added to the release

#322 Update preventing-and-retrying-transitions.md
  guides/v3.5.0/routing/preventing-and-retrying-transitions.md
Labels: Needs to be added to the release

#290 Rearranged order of instructions
  guides/v3.5.0/tutorial/simple-component.md
  guides/v3.6.0/tutorial/simple-component.md
Labels: needs contributor response

#326 Expand addons section
  guides/v3.6.0/addons-and-dependencies/managing-dependencies.md
Labels: needs contributor response
