Repository ember-learn/guides-source, pull requests merged in 2018-10, with the labels that each got.

#169 routes-and-templates: Massage contact template content for linter.
  guides/v2.10.0/tutorial/routes-and-templates.md
  guides/v2.11.0/tutorial/routes-and-templates.md
  guides/v2.12.0/tutorial/routes-and-templates.md
  guides/v2.13.0/tutorial/routes-and-templates.md
  guides/v2.14.0/tutorial/routes-and-templates.md
  guides/v2.15.0/tutorial/routes-and-templates.md
  guides/v2.16.0/tutorial/routes-and-templates.md
  guides/v2.17.0/tutorial/routes-and-templates.md
  guides/v2.18.0/tutorial/routes-and-templates.md
  guides/v2.3.0/tutorial/routes-and-templates.md
  guides/v2.4.0/tutorial/routes-and-templates.md
  guides/v2.5.0/tutorial/routes-and-templates.md
  guides/v2.6.0/tutorial/routes-and-templates.md
  guides/v2.7.0/tutorial/routes-and-templates.md
  guides/v2.8.0/tutorial/routes-and-templates.md
  guides/v2.9.0/tutorial/routes-and-templates.md
  guides/v3.0.0/tutorial/routes-and-templates.md
  guides/v3.1.0/tutorial/routes-and-templates.md
  guides/v3.2.0/tutorial/routes-and-templates.md
  guides/v3.3.0/tutorial/routes-and-templates.md
  guides/v3.4.0/tutorial/routes-and-templates.md
Labels: needs contributor response

#178 fix query params link to be relative #163
  guides/v3.4.0/controllers/index.md
Labels: needs a reviewer

#165 add an intro to Ember Data #164
  guides/v3.4.0/models/index.md
  guides/v3.5.0/models/index.md
Labels: needs reviewer response

#220 Clarify loading search within a route (#35)
  guides/v3.5.0/routing/loading-and-error-substates.md
Labels: needs a reviewer
