Repository ember-learn/guides-source, pull requests merged in 2019-12, with the labels that each got.

#1193 Octane Remove "installing ember" page and link to CLI guides instead
  guides/release/getting-started/index.md
  guides/release/getting-started/intro.md
  guides/release/getting-started/quick-start.md
  guides/release/index.md
  guides/release/pages.yml
Labels: Octane

#1194 Update the upgrade guide
  guides/release/anatomy-of-an-app/index.md
  guides/release/pages.yml
  guides/release/upgrading/current-edition/glimmer-components.md
  guides/release/upgrading/current-edition/index.md
  guides/release/upgrading/current-edition/native-classes.md
  guides/release/upgrading/deprecations.md
  guides/release/upgrading/index.md
Labels: Octane

#1204 [Octane] Slight editorial pass on the quick start
  guides/release/getting-started/quick-start.md
Labels: Octane

#1205 [Octane] Slight tweaks to the new component guides
  guides/release/components/block-content.md
  guides/release/components/component-arguments-and-html-attributes.md
  guides/release/components/conditional-content.md
  guides/release/components/helper-functions.md
  guides/release/components/introducing-components.md
Labels: Octane

#1195 Merge this just before merging `octane` branch - important infra updates
  app/router.js
  app/styles/app.css
  config/environment.js
  guides/release/getting-started/quick-start.md
  public/robots.txt
Labels: Octane, on hold

#1182 Add installation instructions for modifiers
  guides/release/components/template-lifecycle-dom-and-modifiers.md
Labels: needs contributor response
