Repository ember-learn/guides-source, pull requests merged in 2019-03, with the labels that each got.

#477 New Templates intro
  guides/release/templates/handlebars-basics.md
Labels: needs a reviewer

#590 #588 Reading of "Getting Started" and "Services"
  guides/release/getting-started/quick-start.md
  guides/release/services/services.md
Labels: Octane

#594 Reading/Editing/Octaning “Testing” section
  guides/release/testing/acceptance.md
  guides/release/testing/testing-components.md
  guides/release/testing/testing-controllers.md
  guides/release/testing/testing-models.md
  guides/release/testing/unit-testing-basics.md
Labels: Octane, needs a reviewer

#605 [OCTANE] fix small typo, grammar
  guides/release/state-management/index.md
Labels: needs contributor response

#641 update url for the octane banner
  config/environment.js
Labels: Octane, time-sensitive

#607 Update editions.md
  guides/release/upgrading/editions.md
Labels: needs contributor response

#603 [OCTANE] migrate a few other ember data examples
  guides/release/models/customizing-serializers.md
  guides/release/models/defining-models.md
  guides/release/models/relationships.md
  guides/release/tutorial/ember-data.md
Labels: needs a reviewer
