Repository ember-learn/guides-source, pull requests merged in 2019-05, with the labels that each got.

#781 Update installing-addons.md
  guides/v3.3.0/tutorial/installing-addons.md
Labels: needs contributor response

#805 Octane - Replace some references to Computed Properties with Tracked
  guides/release/applications/dependency-injection.md
  guides/release/controllers/index.md
  guides/release/models/relationships.md
  guides/release/routing/query-params.md
  guides/release/services/index.md
  guides/release/templates/built-in-helpers.md
  guides/release/testing/index.md
  guides/release/testing/testing-controllers.md
  guides/release/testing/testing-models.md
  guides/release/testing/testing-routes.md
Labels: Octane

#796 Revising the Octane Upgrade Guide
  guides/release/components/defining-a-component.md
  guides/release/state-management/index.md
  guides/release/upgrading/editions.md
Labels: Octane

#797 Finish converting link-to and input to angle brackets
  guides/release/routing/redirection.md
  guides/release/templates/input-helpers.md
Labels: Octane

#811 Fixes import on test example
  guides/release/testing/index.md
  guides/v3.1.0/testing/index.md
  guides/v3.2.0/testing/index.md
  guides/v3.3.0/testing/index.md
  guides/v3.4.0/testing/index.md
  guides/v3.5.0/testing/index.md
  guides/v3.6.0/testing/index.md
  guides/v3.7.0/testing/index.md
  guides/v3.8.0/testing/index.md
  guides/v3.9.0/testing/index.md
Labels: needs contributor response

#390 Update tutorial to be more consistent with itself and the super-rentals application
  guides/release/tutorial/autocomplete-component.md
Labels: needs contributor response, needs super-rentals PR

#810 Fix broken links in guide.
  guides/release/getting-started/intro.md
Labels: needs contributor response
