Repository ember-learn/guides-source, pull requests merged in 2019-02, with the labels that each got.

#375 Add explicit link to all helpers in the API docs
  guides/v3.7.0/templates/built-in-helpers.md
Labels: needs a reviewer

#454 [OCTANE] Working with JavaScript
  guides/release/getting-started/js-primer.md
  guides/release/object-model/classes-and-instances.md
  guides/release/object-model/reopening-classes-and-instances.md
  guides/release/pages.yml
  guides/release/working-with-javascript/classic-classes.md
  guides/release/working-with-javascript/learning-javascript.md
  guides/release/working-with-javascript/native-classes.md
  guides/release/working-with-javascript/native-vs-classic-class-cheatsheet.md
  yarn.lock
Labels: Octane

#432 components(actions): start converting to class and @action decorator
  guides/release/components/triggering-changes-with-actions.md
Labels: wip - work in progress

#446 change header, rephrase ES6 definition
  guides/release/tutorial/ember-cli.md
Labels: needs contributor response

#501 Add dashes to test module names
  guides/release/testing/testing-components.md
Labels: needs contributor response

#504 [OCTANE] Add edition upgrade guide
  guides/release/upgrading/editions.md
  public/images/upgrading/editions/coherence-chart.png
Labels: Octane, time-sensitive
