Repository ember-learn/guides-source, pull requests merged in 2019-09, with the labels that each got.

#1072 Reference CLI guide in CLI configuration section
  guides/release/configuring-ember/configuring-ember-cli.md
Labels: needs contributor response

#1067 [FEAT] Updates State Management Docs
  .local.dic
  guides/release/pages.yml
  guides/release/state-management/computed-properties.md
  guides/release/state-management/when-to-use-get-and-set.md
Labels: Octane, needs contributor response

#1063 Use Ember Data decorators without parens where possible (#669)
  guides/release/models/customizing-serializers.md
  guides/release/models/defining-models.md
  guides/release/models/pushing-records-into-the-store.md
  guides/release/models/relationships.md
Labels: Octane
